config/routes.rb
WhatToEat::Application.routes.draw do
  root :to => "restaurants#index"

  # Admin Controllers
  match "/admin/authenticate" => "admins#authenticate", as: "authenticate"
  match "/admin/login" => "admins#login", as: 'login'
  match "/admin/logout" => "admins#logout", via: :delete

  # Restaurant Controllers
  match "admin/show_all" => "restaurants#show_all", as: "show_all"  
  match "admin/restaurant/:id/edit" => "restaurants#edit", as: "edit"
  match "admin/restaurant/:id/perform_edit" => "restaurants#perform_edit", as: "perform_edit", via: :put
  match "admin/restaurant/insert" => "restaurants#insert", as: "insert"
  match "admin/restaurant/new" => "restaurants#new", as: "new", via: :post
  match "admin/restaurant/:id/destroy" => "restaurants#destroy", as: "destroy", via: :delete
  match "index" => "restaurants#index", as: "index", via: :get
  match "decide" => "restaurants#show_random_restaurant", as: "decide_restaurant", via: :post
end

app/models/exceptions/user_exception.rb
class UserException < StandardError
  def initialize(message)
    @message = message
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :location, :name
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base 
  include BCrypt
  
  attr_accessible :password, :username
  before_save :encrypt_password
  after_save :empty_password


  def self.authenticate(username, password) 
    user = User.find_by_username(username)
    if user && user.password == BCrypt::Engine.hash_secret(password, user.salt)
      user.id
    else
      raise UserException.new("Authentication Failed")
    end 
  end

  private
  def encrypt_password
    if self.password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.password = BCrypt::Engine.hash_secret(self.password, self.salt)
    end  
  end

  def empty_password
    self.password = ""
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def authenticate
    begin
      session[:user_id] = User.authenticate(params[:username], params[:password])
      redirect_to show_all_path
    rescue
      redirect_to login_path
    end
  end

  def login

  end

  def logout
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_filter :require_login, except: [:index, :show_random_restaurant]

  def show_all
    @restaurants = Restaurant.all
  end

  def edit
    @restaurant = Restaurant.find_by_id(params[:id])
  end

  def perform_edit
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(params[:restaurant])
      redirect_to show_all_path
    else
      redirect_to edit_path(@restaurant)
    end
  end

  def require_login
    if !session[:user_id]
      redirect_to login_path
    end
  end

  def insert
    @restaurant = Restaurant.new    
  end

  def new
    restaurant = Restaurant.new(params[:restaurant])
    if restaurant.save
      redirect_to show_all_path
    else
      redirect_to insert_path
    end
  end

  def destroy
    restaurant = Restaurant.find(params[:id])
    restaurant.destroy
    redirect_to show_all_path 
  end

  def index
  end

  def show_random_restaurant
    total_restaurant_count = Restaurant.count

    if total_restaurant_count > 0
      @restaurant = Restaurant.offset(Random.rand(total_restaurant_count)).first
    end
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/login.html.erb
<h1>Admin Login</h1>
<%= form_tag(controller: "admins", action: "authenticate", method: :post) do %>
  <%= label_tag(:username, "Username : ") %>
  <%= text_field_tag(:username) %><br />
  <%= label_tag(:password, "Password : ") %>
  <%= password_field_tag(:password) %>
  <%= submit_tag("Login") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhatToEat</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= form_for(@restaurant, url: perform_edit_path(@restaurant), html: { method: :put }) do |f| %>
  <%= f.label :name  %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :location %>
  <%= f.text_field :location %>
  <br />
  <%= f.submit "Edit" %>
<% end %>

app/views/restaurants/index.html.erb
<h1>What to Eat</h1>
<%= form_tag(controller: "restaurants", action: "show_random_restaurant", method: "post") do %>
  <%= submit_tag("decide") %>
<% end %>

app/views/restaurants/insert.html.erb
<h1>Insert new restaurant</h1>
<%= form_for(@restaurant, url: new_path(@restaurant), html: { method: :post }) do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  <br />
  <%= f.label :location, "Location" %>
  <%= f.text_field :location %>
  <br />
  <%= f.submit "Insert" %>
<% end %> 

app/views/restaurants/show_all.html.erb
<h1>Admin Page</h1>
<%= link_to "Logout", { controller: "admins", action: "logout"} , method: :delete %>
<h2>Restaurant List</h2>
<%= link_to "Create new restaurant", insert_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
  </tr>
  <% @restaurants.each do |restaurant| %>
    <tr>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.location %></td>
      <td><%= link_to "edit", edit_path(restaurant.id), class: "edit"  %></td>
      <td><%= link_to "delete", destroy_path(restaurant.id), class: "delete", method: :delete %>
    </tr>
  <% end %>
</table>

app/views/restaurants/show_random_restaurant.html.erb
<h1>What to Eat</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
  </tr>
  <tr>
    <td><%= @restaurant.name %></td>
    <td><%= @restaurant.location %></td>
  </tr>
</table>